#! /bin/sh
echo $$ > /tmp/steamos-update.pid
/usr/bin/swupd update
version=`printf '%b\n' "$(cat /etc/os-release | grep VERSION_ID)"| sed 's/[^0-9]*//g'`
destdir=/etc/lsb-release
if [ -f "$destdir" ]
then
   echo "DISTRIB_DESCRIPTION=\"Clear Linux $version\"" > "$destdir"
fi
rm /tmp/steamos-update.pid